CREATE TABLE usuarios (
  data_ultima_alteracao timestamp(6),
  id bigint generated by default as identity,
  cep varchar(255),
  cidade varchar(255),
  email varchar(255) unique,
  estado varchar(255),
  login_username varchar(255) unique,
  nome varchar(255),
  numero varchar(255),
  rua varchar(255),
  senha varchar(255) not null,
  tipo_usuario varchar(255) check ((tipo_usuario in ('CLIENTE','DONO_RESTAURANTE'))),
  primary key (id)
);